name: bluetooth_low_energy_backend
description: "Bluetooth Low Energy backend"
version: 0.5.1
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/bluetooth_low_energy_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.4.0
  bluetooth_low_energy: ^6.2.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
