name: ble_backend_factory
description: "BLE central factory of choosed backends"
version: 1.4.3
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/ble_backend_factory

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.4.0
  flutter_reactive_ble: ^5.4.0
  flutter_reactive_ble_backend: ^1.4.0
  flutter_web_bluetooth: ^1.1.0
  flutter_web_bluetooth_backend: ^1.4.1
  bluez: ^0.8.3
  bluez_backend: ^0.5.0
  universal_ble: ^1.1.0
  universal_ble_backend: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
